apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    app: auth-service
data:
  DB_HOST: "172.17.0.1"
  DB_PORT: "5432"
  DB_NAME: "prg_dev"
  CORS_ORIGINS: "http://localhost:3000"
  JAVA_OPTS: "-Xms256m -Xmx512m"
