apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search-service
    app.kubernetes.io/part-of: screen-recorder
spec:
  type: ClusterIP
  selector:
    app: search-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
