apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data
  labels:
    app: opensearch
    app.kubernetes.io/part-of: screen-recorder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
