apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: opensearch
    app.kubernetes.io/part-of: screen-recorder
spec:
  type: ClusterIP
  selector:
    app: opensearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
