apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-gateway-config
  labels:
    app: ingest-gateway
data:
  DB_HOST: "172.17.0.1"
  DB_PORT: "5432"
  DB_NAME: "prg_dev"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  S3_ENDPOINT: "http://minio:9000"
  S3_REGION: "us-east-1"
  S3_BUCKET: "prg-segments"
  S3_PRESIGN_EXPIRY: "300"
  JAVA_OPTS: "-Xms256m -Xmx768m"
