apiVersion: v1
kind: Service
metadata:
  name: playback-service
  labels:
    app: playback-service
    app.kubernetes.io/part-of: screen-recorder
spec:
  type: ClusterIP
  selector:
    app: playback-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
